services:
  - type: web
    name: smartcafe
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: "3.11"
    envVars:
      - key: PORT
        value: 5000
